language: go
install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
