baseURL = "https://www.karankhanchandani.com"
languageCode = "en-us"
title = "Karan Khanchandani"
defaultContentLanguage = "en"

relativeURLs = true
canonifyURLs = true

googleAnalytics = "UA-105234182-1"
#disqusShortname = ""

# hugo-xmin specific variables
theme = "karan-website"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"


[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 2
#[[menu.main]]
#    name = "Projects"
#    identifier = "projects"
#    url = "/projects/"
#    weight = 3
#[[menu.main]]
#    name = "Skills"
#    identifier = "skills"
#    url = "/skills/"
#    weight = 4
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    url = "/tutorials/"
    weight = 5
[[menu.main]]
    name = "Contact Me"
    identifier = "contactme"
    url = "/contactme/"
    weight = 6

[author]
  name = "Karan Khanchandani"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  discord = "https://discord.gg/EgBenrW"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  twitter = "skycoinproject"
  twitterAnalytics = "ny03t"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/karan-khanchandani-47a22569/"
  icon = "fab fa-linkedin"
[[params.social]]
  name = "Medium"
  url = "https://medium.com/@karankhanchandani"
  icon = "fab fa-medium"
[[params.social]]
  name = "Github"
  url = "https://github.com/Karan-Khanchandani"
  icon = "fab fa-github-square"
[[params.social]]
  name = "Stackoverflow"
  url = "https://stackoverflow.com/users/3873874"
  icon = "fab fa-stack-overflow"
#[[params.social]]
#  name = "Codepen"
#  url = "https://codepen.io/Ronin_47/"
#  icon = "fab fa-codepen"
#[[params.social]]
#  name = "Hackerrank"
#  url = "https://www.hackerrank.com/ronin_47"
#  icon = "fab fa-hackerrank"
#[[params.social]]
#  name = "Facebook"
#  url = "https://www.facebook.com/profile.php?id=100009782580452"
#  icon = "fab fa-facebook-square"
#  [[params.social]]
#  name = "Instagram"
#  url = "https://www.instagram.com/karankhanchandani47/"
#  icon = "fab fa-instagram"   