#baseURL = "https://www.karankhanchandani.com"
baseURL = "/"
languageCode = "en-us"
title = "Karan Khanchandani"
defaultContentLanguage = "en"

relativeURLs = true
canonifyURLs = true

googleAnalytics = "UA-105234182-1"
#disqusShortname = ""

# hugo-xmin specific variables
theme = "karan-website"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Skills"
    identifier = "skills"
    url = "/skills/"
    weight = 4
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    url = "/tutorials/"
    weight = 5
[[menu.main]]
    name = "Contact Me"
    identifier = "contactme"
    url = "/contactme/"
    weight = 6

[author]
  name = "Karan Khanchandani"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  discord = "https://discord.gg/EgBenrW"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  twitter = "skycoinproject"
  twitterAnalytics = "ny03t"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/karan-khanchandani-47a22569/"
  image = "images/linkedin.svg"
[[params.social]]
  name = "Medium"
  url = "https://twitter.com/skycoinproject"
  image = "images/medium.svg"
[[params.social]]
  name = "Github"
  url = "https://www.facebook.com/SkycoinOfficial/"
  image = "images/facebook.svg"
[[params.social]]
  name = "Codepen"
  url = "https://www.instagram.com/skycoinproject/"
  image = "images/codepen.svg"
[[params.social]]
  name = "Hackerrank"
  url = "https://github.com/skycoin/skycoin"
  image = "images/hackerrank.png"
[[params.social]]
  name = "SPOJ"
  url = "https://www.youtube.com/c/Skycoin"
  image = "images/spoj.jpg"
[[params.social]]
  name = "Codeforces"
  url = "https://www.reddit.com/r/SkycoinProject"
  image = "images/codeforces.png"
[[params.social]]
  name = "Codechef"
  url = "https://itunes.apple.com/nl/podcast/skycoin/id1348472259?l=en"
  image = "images/codechef.jpg"  
[[params.social]]
  name = "Hackerearth"
  url = "https://discord.gg/EgBenrW"
  image = "images/hackerearth.png" 
[[params.social]]
  name = "Facebook"
  url = "https://t.me/Skycoin"
  image = "images/facebook.svg" 
  [[params.social]]
  name = "Instagram"
  url = "https://t.me/Skycoin"
  image = "images/instagram.svg"   